import { useCallback, useState } from "react";
import { IUserRole } from "@interfaces/invitation.interface";
import { InvitationFormValues } from "@validations/invitation.validations";

export function useInvitationPreview() {
  const [showPreview, setShowPreview] = useState(false);

  const handleShowPreview = useCallback(() => {
    setShowPreview(true);
  }, []);

  const handleClosePreview = useCallback(() => {
    setShowPreview(false);
  }, []);

  const getTemplateVariables = useCallback(
    (formData: InvitationFormValues, selectedRole: IUserRole | null) => {
      const fullName = "James Blunt";
      // `${formData?.personalInfo?.firstName} ${formData?.personalInfo?.lastName}`.trim();

      const baseVariables = {
        companyName: "Property Management System",
        inviteeName: fullName || "there",
        inviterName: "System Administrator",
        role: selectedRole || "Team Member",
        customMessage: formData.metadata?.inviteMessage || "",
        expiresAt: new Date(
          Date.now() + 7 * 24 * 60 * 60 * 1000
        ).toLocaleDateString(),
        invitationUrl: "#", // would be generated by backend
        inviteeEmail: formData.inviteeEmail || "recipient@email.com",
        expectedStartDate:
          formData.metadata?.expectedStartDate?.toLocaleDateString() || "",
      };

      // Add role-specific variables
      if (selectedRole === "EMPLOYEE" && formData.employeeInfo) {
        return {
          ...baseVariables,
          jobTitle: formData.employeeInfo.jobTitle || "",
          department: formData.employeeInfo.department || "",
          employeeId: formData.employeeInfo.employeeId || "",
          reportsTo: formData.employeeInfo.reportsTo || "",
          startDate:
            formData.employeeInfo.startDate?.toLocaleDateString() || "",
        };
      }

      if (selectedRole === "VENDOR" && formData.vendorInfo) {
        return {
          ...baseVariables,
          companyName:
            formData.vendorInfo.companyName || baseVariables.companyName,
          businessType: formData.vendorInfo.businessType || "",
          serviceArea: formData.vendorInfo.serviceArea?.maxDistance || "",
          contactPersonName: formData.vendorInfo.contactPerson?.name || "",
          contactPersonEmail: formData.vendorInfo.contactPerson?.email || "",
          contactPersonPhone: formData.vendorInfo.contactPerson?.phone || "",
        };
      }

      return baseVariables;
    },
    []
  );

  return {
    showPreview,
    handleShowPreview,
    handleClosePreview,
    getTemplateVariables,
  };
}
